sudo: required

services:
  - docker

before_script:
  - docker build --tag powerhome/clockr-builder --file Dockerfile.builder .

script: docker run --interactive --rm --volume $(pwd):/src/clockr --env MIX_ENV=test powerhome/clockr-builder mix do deps.get, test, credo

after_success:
  - docker run --interactive --rm --volume $(pwd):/src/clockr --env MIX_ENV=prod powerhome/clockr-builder
  - docker build --tag powerhome/clockr --file Dockerfile.run .
